# Generated by Django 4.0.4 on 2023-03-07 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFarmImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('farm_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_farm_images', to='core.farmvideo')),
            ],
            options={
                'verbose_name': 'VideoFarmImages',
                'verbose_name_plural': 'VideoFarmImagess',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
