# Generated by Django 4.0.4 on 2023-03-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disease_alter_videofarmimages_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detactfarmimages',
            options={'verbose_name': 'DetactFarmImages', 'verbose_name_plural': 'DetactFarmImagess'},
        ),
        migrations.AddField(
            model_name='farmvideo',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('processing', 'processing')], default='completed', max_length=10, verbose_name='Status'),
        ),
    ]
