# Generated by Django 4.0.4 on 2023-03-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_detactfarmimages_options_farmvideo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmvideo',
            name='moisture_farm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmvideo',
            name='ph_farm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmvideo',
            name='temperature',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmvideo',
            name='total_amt_salt',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmvideo',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('processing', 'processing')], default='processing', max_length=10, verbose_name='Status'),
        ),
    ]
