# Generated by Django 4.0.4 on 2023-03-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_farmvideo_moisture_farm_farmvideo_ph_farm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmvideo',
            name='moisture_farm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='farmvideo',
            name='ph_farm',
            field=models.FloatField(),
        ),
    ]
