# Generated by Django 4.0.4 on 2023-03-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='temperature_farm_less',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='temperature_farm_more',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
