# Generated by Django 4.0.4 on 2023-05-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_crop_temperature_farm_less_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='image',
            field=models.ImageField(null=True, upload_to='disease_images'),
        ),
    ]
